### PR TITLE
The number text for a list should never be abbreviated via "..." #10

### PR DESCRIPTION
**Pull request by dlemmermann**
Replaced the call label.setMinWidth(20) with label.setMinWidth(Region.USE_PREF_SIZE).

### CODE REVIEW

**Comment by FlorianKirmaier** [comment]
Seems to me more like wrong layouting in JavaFX. The minWidth is set, to make sure each line starts at the same position.
But the Label should still use it's prefWidth, if it's bigger. As far as my understanding goes, "..." shouldn't be shown in the current version, if everything works correct.

**Comment by dlemmermann** [comment]
ok, but a numbered item like "1." or "8." needs more than 20 pixels it seems.

**Comment by FlorianKirmaier** [comment]
Screenshot 2021-07-06 at 17 38 39
This is how it looks. Looks to me like a layouting bug somewhere. The HBox doesn't share the available space properly, when there are multiple lines used.

**Comment by FlorianKirmaier** [comment]
Fixed in a slightly different way, in 0.2.4 https://github.com/JPro-one/markdown-javafx-renderer/commit/9cc7c17adedb6ddd853819c629211b6df7902295
The right part now has a minimal prefwidth, but grows always. This way it doesn't take space from the left.

**Pull request closed without merging**
